baseURL = 'http://hackerdemic.com/'
languageCode = 'en-us'
title = 'hackerdemic'
theme = 'm10c'
sectionPagesMenu = 'main'

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'home'
    url = '/'
    weight = 1
  [[menu.main]]
    identifier = 'tags'
    name = 'tags'
    url = '/tags/'
    weight = 2
  [[menu.main]]
    identifier = 'about'
    name = 'whoami'
    url = '/whoami/'
    weight = 3

[params]
  author = 'ATHL337'
  description = 'ğ™„ğ™©â€™ğ™¨ ğ™£ğ™¤ğ™© ğ™¤ğ™«ğ™šğ™§ ğ™¬ğ™ğ™šğ™£ ğ™®ğ™¤ğ™ª ğ™¡ğ™¤ğ™¨ğ™š, ğ™ğ™©â€™ğ™¨ ğ™¤ğ™«ğ™šğ™§ ğ™¬ğ™ğ™šğ™£ ğ™®ğ™¤ğ™ª ğ™¦ğ™ªğ™ğ™©.'
  menu_item_separator = ' - '
  opengraph = true
  
  [[params.social]]
    icon = 'github'
    name = 'Github'
    url = 'https://github.com/ATHL337'

  [[params.social]]
    icon = "linkedin"
    name = "LinkedIn"
    url = 'linkedin.com/in/alfredopelaez/'

  # Default theme
  #[params.style]
  #  darkestColor = '#242930'
  #  darkColor = '#353b43'
  #  lightColor = '#afbac4'
  #  lightestColor = '#ffffff'
  #  primaryColor = '#57cc8a'

  # Green theme
  #[params.style]
  #  darkestColor = '#315659'
  #  darkColor = '#253031'
  #  lightColor = '#96a879'
  #  lightestColor = '#fff'
  #  primaryColor = '#dad865'

  # Red theme
  #[params.style]
  #  darkestColor = '#d35050'
  #  darkColor = '#212121'
  #  lightColor = '#d6d6d6'
  #  lightestColor = '#d3d3d3'
  #  primaryColor = '#ffffff'

  [[params.analytics]]
  googleAnalytics = 'G-EB0VH10EH1'
